#!/usr/bin/env bash
#
# Grab up to seven entries from Hackaday for a year in the past. Returns URLs,
# separated by newline.
#
# Usage: fetch-hackaday-entries <yearsago>
#
#   <yearsago> a number of years in the past
#
# EXAMPLE
#
#   The command:
#
#     fetch-hackaday-entries 10
#
#   Will display:
#
#     https://hackaday.com/2009/10/06/exploding-processors-for-real/
#     https://hackaday.com/2009/10/06/halloween-prop-bigmouth-billy-bass/
#     https://hackaday.com/2009/10/06/five-concept-mice-add-multi-touch-control/
#     [...]
#
#   In other words:
#
#     Get entry URLs from this day 10 years ago.

set -e
set -o pipefail

date=$(date -v "-$1y" +"%Y/%m/%d" 2> /dev/null) || date=$(date +%Y/%m/%d --date="$1 years ago")

curl --silent --show-error "https://hackaday.com/$date/" |
grep 'bookmark' |
cut -d '"' -f 4
