#!/usr/bin/env bash
#
# Grab up to seven entries from Hackaday for a specific date. Returns URLs,
# separated by newline.
#
# Usage: fetch-entries <date>
#
#   <date> on the format YYYY/MM/DD
#
# EXAMPLE
#
#   The command:
#
#     fetch-entries 2009/10/06
#
#   Will display:
#
#     https://hackaday.com/2009/10/06/exploding-processors-for-real/
#     https://hackaday.com/2009/10/06/halloween-prop-bigmouth-billy-bass/
#     https://hackaday.com/2009/10/06/five-concept-mice-add-multi-touch-control/
#     [...]
#
#   In other words:
#
#     Get entry URLs published on October 6 2009.

set -e
set -o pipefail

curl --silent --show-error "https://hackaday.com/$1/" |
grep 'bookmark' |
cut -d '"' -f 4
