#!/usr/bin/env bash
#
# Grab up to seven entries from Hackaday for a date in the past. Returns URLs,
# separated by newline.
#
# Usage: fetch-hackaday-entries <val>
#
#   <val> follows the same format as date(1)
#
# EXAMPLE
#
#   The command:
#
#     fetch-hackaday-entries "10 years ago"
#
#   Will display:
#
#     https://hackaday.com/2009/10/06/exploding-processors-for-real/
#     https://hackaday.com/2009/10/06/halloween-prop-bigmouth-billy-bass/
#     https://hackaday.com/2009/10/06/five-concept-mice-add-multi-touch-control/
#     [...]
#
#   In other words:
#
#     Get entry URLs from this day 10 years ago.

set -e
set -o pipefail

date=$(date +%Y/%m/%d -d "$1")

curl --silent --show-error "https://hackaday.com/$date/" |
grep 'bookmark' |
cut -d '"' -f 4
